### ISSUE TITLE
java decrypt error

### ISSUE THREAD

**Issue by lsqswl** [travist/jsencrypt#138]
Exception in thread "main" javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:380)
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:291)
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2223)

**Comment by lsqswl** [comment]
https://github.com/lsqswl/rsaencrypt
