### ISSUE TITLE
Support node.js ?  ReferenceError: window is not defined

### ISSUE THREAD

**Issue by KingAmo** [travist/jsencrypt#297]
- node `v16.19.1`
- jsencrypt `3.3.2`
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/x/x/node_modules/jsencrypt/bin/jsencrypt.js:18:4)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
```

**Comment by zhumenglonge** [comment]
降为3.2.1；在首行加上global.window = this试试

**Comment by lanzhsh** [comment]
这种线上打包 还要手动更改node_modules 包, 太不友好了

**Comment by pluto369** [comment]
> * node `v16.19.1`
> * jsencrypt `3.3.2`
> 
> ```
> ReferenceError: window is not defined
>     at Object.<anonymous> (/Users/x/x/node_modules/jsencrypt/bin/jsencrypt.js:18:4)
>     at Module._compile (node:internal/modules/cjs/loader:1191:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
>     at Module.load (node:internal/modules/cjs/loader:1069:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
>     at async loadESM (node:internal/process/esm_loader:91:5)
> ```

`
import JSEncrypt from 'jsencrypt/lib/index.js'
const crypt = new JSEncrypt.default()
`

**Comment by pluto369** [comment]
```
import JSEncrypt from 'jsencrypt/lib/index.js'
const crypt = new JSEncrypt.default()
```
在node中使用可以这样用

**Comment by airwin** [comment]
> 降为3.2.1；在首行加上global.window = this试试

加 global.window = this 可用

**Comment by yantx** [comment]
今天也遇到了这个问题mock模拟数据时使用了jsencrypt加密出现的版本3.3.2
引入方式：
 ```js
  import JSEncrypt from 'jsencrypt/bin/jsencrypt.min'
  let decrypt = new JSEncrypt()
 ```
 解决方式：在jsencrypt.min.js文件中添加如下代码
 ```js
 const window=this
 ```

**Comment by lancelot-song** [comment]
Because import `jsencrypt` before `global.window` not create，it will result load to failed `global.window`，so you should use js the single-threaded，let `global.window` is created  before to `import jsencrypt`, try
```JavaScript
(async () => {
  global.window = this;
  const JSEncrypt = await import('jsencrypt');
  const jsencrypt = new JSEncrypt.default();
  jsencrypt.setPublicKey(publicKey); // u public key
  console.log(`token:\r\n${jsencrypt.encrypt(RSA_VALUE)}`);
})();
```
